# Configure License Key
license:
  # The server name is recommended if you run the license key on multiple servers. Should be unique.
  server-name: ""
  # License key can be obtained by contacting Xemu on Discord (@xemuu) or sending a message on BuiltByBit: @Xemu
  license-key: ""

big-win-announce:
  enabled: true
  aboveMultiplier: 1.00
  command: "broadcast &e&l(CASINO) &a%username%&7 just won &e%winning% &7from &a%game% &7(&f%multiplier%x&7)"


# Enable or disable games
# When disabled, also make sure to remove the item from the GUI
games:
  coinflip: true
  mines: true
  crash: true
  wheel: true
  slots: true

# This is to configure the slots in the main GUI.
# Type 0 to remove them from the GUI.
casino-gui:
  crash: 20
  wheel: 21
  slots: 24
  coinflip: 22
  mines: 23

coinflip:
  min-bet: 10
  max-bet: 10000
mines:
  min-bet: 10
  max-bet: 10000
  base-mine-chance: 0.2
  base-min-multiplier: 0.05
  base-max-multiplier: 0.15
  difficulty:
    easy: 0.5
    normal: 1.0
    hard: 1.5
crash:
  min-bet: 10
  max-bet: 10000
  max-multiplier: 100.0
  base-multiplier: 0.01
  crash-chance: 0.01
wheel:
  min-bet: 10
  max-bet: 10000
  items: [
    0.1, 0.25, 0, 0.5, 0, 1, 1, 2, 50, 0.1, 0.25, 1, 0.43, 55, 0, 0, 200, 0, 0.50, 1, 1
  ]
slots:
  min-bet: 10
  max-bet: 10000
  items:
    emerald:
      chance: 0.01
      multiplier: 100
    diamond:
      chance: 0.05
      multiplier: 50
    gold_ingot:
      chance: 0.1
      multiplier: 5
    iron_ingot:
      chance: 0.125
      multiplier: 2
    coal:
      chance: 0.15
      multiplier: 1
